// Generated by CoffeeScript 1.10.0
(function() {
  var Promise;

  Promise = require('bluebird');

  describe('A ReadmeCreator', function() {
    return it.only('creates a README based on given options and a template', function() {
      var ReadmeCreator;
      ReadmeCreator = require('./run.coffee');
      return ReadmeCreator.run(['node', 'readme-creator', '-d', '--add-desc', 'test']).then(function() {
        return expect(fs.readFileSync('README.md', {
          encoding: 'utf-8'
        })).to.equal('test');
      });
    });
  });

}).call(this);
