// Generated by CoffeeScript 1.10.0
(function() {
  var BadgeParser, Promise, badgeData, mustache, winston;

  winston = require('winston');

  Promise = require('bluebird');

  mustache = require('mustache');

  badgeData = require('../../data/badges.json');

  module.exports = BadgeParser = (function() {
    BadgeParser.name = "BadgeParser";

    function BadgeParser(options) {
      var base;
      this.options = options;
      if (this.options == null) {
        this.options = {};
      }
      if ((base = this.options).badges == null) {
        base.badges = ['npm-version', 'travis', 'coveralls', 'dependencies', 'devDependencies', 'gitter'];
      }
    }

    BadgeParser.prototype.run = function(pkg) {
      winston.info("Creating badges");
      if (pkg.git == null) {
        return Promise.resolve([]);
      }
      winston.debug(" Adding badges " + this.options.badges);
      return Promise.resolve(this.options.badges.map(function(badgeName) {
        return {
          name: mustache.render(badgeData[badgeName].name, pkg),
          img: mustache.render(badgeData[badgeName].img, pkg),
          url: mustache.render(badgeData[badgeName].url, pkg)
        };
      }));
    };

    return BadgeParser;

  })();

}).call(this);
