// Generated by CoffeeScript 1.10.0
(function() {
  var DescriptionParser, Promise, os, winston;

  winston = require('winston');

  Promise = require('bluebird');

  os = require('os');

  module.exports = DescriptionParser = (function() {
    DescriptionParser.name = "DescriptionParser";

    function DescriptionParser(options) {
      var base;
      this.options = options;
      if (this.options == null) {
        this.options = {};
      }
      if ((base = this.options).addDesc == null) {
        base.addDesc = '';
      }
      if (Array.isArray(this.options.addDesc)) {
        this.options.addDesc = this.options.addDesc.join('');
      }
    }

    DescriptionParser.prototype.run = function(pkg) {
      winston.info("Creating description");
      if (this.options.addDesc.length > 0) {
        winston.debug(" Adding additional description");
        return Promise.resolve(pkg.description + os.EOL + os.EOL + this.options.addDesc);
      } else {
        winston.debug(" Not adding additional description");
        return Promise.resolve(pkg.description);
      }
    };

    return DescriptionParser;

  })();

}).call(this);
