// Generated by CoffeeScript 1.10.0
(function() {
  var InstallParser, Promise, logger;

  logger = require('../logger');

  Promise = require('bluebird');

  module.exports = InstallParser = (function() {
    InstallParser.name = "InstallParser";

    function InstallParser(options) {
      var base, base1;
      this.options = options;
      if (this.options == null) {
        this.options = {};
      }
      if ((base = this.options).modules == null) {
        base.modules = ['CommonJS'];
      }
      if ((base1 = this.options).unpkg == null) {
        base1.unpkg = false;
      }
    }

    InstallParser.prototype.run = function(pkg) {
      logger.info("Creating installation info");
      logger.debug(" Adding modules " + this.options.modules);
      if (this.options.unpkg) {
        logger.debug(" Adding unpkg");
      }
      return Promise.resolve({
        modules: {
          names: this.options.modules.map(function(module) {
            return {
              name: module
            };
          })
        },
        unpkg: this.options.unpkg
      });
    };

    return InstallParser;

  })();

}).call(this);
