// Generated by CoffeeScript 2.3.2
(function() {
  var DocsParser, mockFs;

  mockFs = require('mock-fs');

  DocsParser = require('../components/docs.coffee');

  describe("A DocsParser", function() {
    var pkg;
    pkg = null;
    beforeEach(function() {
      pkg = require('../../package.json');
      return pkg.git = {
        user: "dbartholomae",
        repo: "readme-creator",
        branch: "master"
      };
    });
    afterEach(function() {
      return mockFs.restore();
    });
    it("returns a rawgit url if the doc file exists", function() {
      var docsParser;
      mockFs({
        'doc/index.html': "Some documentation. Oh no, where's the html?"
      });
      docsParser = new DocsParser();
      return expect(docsParser.run(pkg)).to.eventually.deep.equal('https://rawgit.com/dbartholomae/readme-creator/master/doc/index.html');
    });
    it("returns null if the doc file doesn't exist", function() {
      var docsParser;
      mockFs();
      docsParser = new DocsParser();
      return expect(docsParser.run(pkg)).to.eventually.deep.equal(null);
    });
    it("returns null if it isn't a git repository", function() {
      var docsParser;
      pkg.git = null;
      mockFs({
        'doc/index.html': "Some documentation. Oh no, where's the html?"
      });
      docsParser = new DocsParser();
      return expect(docsParser.run(pkg)).to.eventually.deep.equal(null);
    });
    return it("accepts different doc files", function() {
      var docsParser;
      pkg.directories.doc = 'docs';
      mockFs({
        'docs/index.htm': "Some documentation. Oh no, where's the html?"
      });
      docsParser = new DocsParser({
        docFile: 'index.htm'
      });
      return expect(docsParser.run(pkg)).to.eventually.deep.equal('https://rawgit.com/dbartholomae/readme-creator/master/docs/index.htm');
    });
  });

}).call(this);
