// Generated by CoffeeScript 1.10.0
(function() {
  var PkgParser;

  PkgParser = require('../components/pkg.coffee');

  describe("A PkgParser", function() {
    var pkg;
    pkg = null;
    beforeEach(function() {
      pkg = require('../../package.json');
      return pkg.git = {
        user: "dbartholomae",
        repo: "readme-creator",
        branch: "master"
      };
    });
    return it("should parse pkg info correctly", function() {
      var pkgParser;
      pkgParser = new PkgParser();
      return expect(pkgParser.run(pkg)).to.eventually.deep.equal({
        name: pkg.name,
        version: pkg.version,
        "private": pkg["private"],
        preferGlobal: pkg.preferGlobal
      });
    });
  });

}).call(this);
